"""Add User

Revision ID: 178eac64933b
Revises: 17ba1618c33d
Create Date: 2026-02-20 13:09:41.537660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178eac64933b'
down_revision = '17ba1618c33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
